//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltraFoxyChickenFlightX.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UltraFoxyChickenFlightX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AngryCloudFileName1 {
            get {
                return ResourceManager.GetString("AngryCloudFileName1", resourceCulture);
            }
        }
        
        internal static string AngryCloudFileName2 {
            get {
                return ResourceManager.GetString("AngryCloudFileName2", resourceCulture);
            }
        }
        
        internal static string BackgroundFileName {
            get {
                return ResourceManager.GetString("BackgroundFileName", resourceCulture);
            }
        }
        
        internal static string BadTreeSpriteFileName {
            get {
                return ResourceManager.GetString("BadTreeSpriteFileName", resourceCulture);
            }
        }
        
        internal static string FarmerFileName {
            get {
                return ResourceManager.GetString("FarmerFileName", resourceCulture);
            }
        }
        
        internal static string GoodTreeSoundName {
            get {
                return ResourceManager.GetString("GoodTreeSoundName", resourceCulture);
            }
        }
        
        internal static string FoxyHappy1FileName {
            get {
                return ResourceManager.GetString("FoxyHappy1FileName", resourceCulture);
            }
        }
        
        internal static string FoxyScared1FileName {
            get {
                return ResourceManager.GetString("FoxyScared1FileName", resourceCulture);
            }
        }
        
        internal static string GoodTreeSpriteFileName {
            get {
                return ResourceManager.GetString("GoodTreeSpriteFileName", resourceCulture);
            }
        }
        
        internal static string HappyCloudFileName1 {
            get {
                return ResourceManager.GetString("HappyCloudFileName1", resourceCulture);
            }
        }
        
        internal static string HappyCloudFileName2 {
            get {
                return ResourceManager.GetString("HappyCloudFileName2", resourceCulture);
            }
        }
        
        internal static string HappyCloudSoundName {
            get {
                return ResourceManager.GetString("HappyCloudSoundName", resourceCulture);
            }
        }
        
        internal static string HenhouseFileName {
            get {
                return ResourceManager.GetString("HenhouseFileName", resourceCulture);
            }
        }
        
        internal static string NumbersSpriteFileName {
            get {
                return ResourceManager.GetString("NumbersSpriteFileName", resourceCulture);
            }
        }
        
        internal static string AngryCloudSoundName {
            get {
                return ResourceManager.GetString("AngryCloudSoundName", resourceCulture);
            }
        }
        
        internal static string MenuContinueFileName {
            get {
                return ResourceManager.GetString("MenuContinueFileName", resourceCulture);
            }
        }
        
        internal static string MenuGameTitleFileName {
            get {
                return ResourceManager.GetString("MenuGameTitleFileName", resourceCulture);
            }
        }
        
        internal static string MenuNewGameFileName {
            get {
                return ResourceManager.GetString("MenuNewGameFileName", resourceCulture);
            }
        }
        
        internal static string MenuQuitFileName {
            get {
                return ResourceManager.GetString("MenuQuitFileName", resourceCulture);
            }
        }
        
        internal static string BadTreeSoundName {
            get {
                return ResourceManager.GetString("BadTreeSoundName", resourceCulture);
            }
        }
        
        internal static string FoxyStandingFileName {
            get {
                return ResourceManager.GetString("FoxyStandingFileName", resourceCulture);
            }
        }
        
        internal static string BirdFlapFileName {
            get {
                return ResourceManager.GetString("BirdFlapFileName", resourceCulture);
            }
        }
        
        internal static string MainMenuSoundName {
            get {
                return ResourceManager.GetString("MainMenuSoundName", resourceCulture);
            }
        }
        
        internal static string BackgroundMusicFileName {
            get {
                return ResourceManager.GetString("BackgroundMusicFileName", resourceCulture);
            }
        }
        
        internal static string HenhouseSoundFileName {
            get {
                return ResourceManager.GetString("HenhouseSoundFileName", resourceCulture);
            }
        }
        
        internal static string FoxyHappy2FileName {
            get {
                return ResourceManager.GetString("FoxyHappy2FileName", resourceCulture);
            }
        }
        
        internal static string FoxyScared2FileName {
            get {
                return ResourceManager.GetString("FoxyScared2FileName", resourceCulture);
            }
        }
        
        internal static string MainMenuNewGameHoverFileName {
            get {
                return ResourceManager.GetString("MainMenuNewGameHoverFileName", resourceCulture);
            }
        }
        
        internal static string MainMenuQuitHoverFileName {
            get {
                return ResourceManager.GetString("MainMenuQuitHoverFileName", resourceCulture);
            }
        }
        
        internal static string LogoFileName {
            get {
                return ResourceManager.GetString("LogoFileName", resourceCulture);
            }
        }
        
        internal static string FarmerJoeSoundFileName {
            get {
                return ResourceManager.GetString("FarmerJoeSoundFileName", resourceCulture);
            }
        }
        
        internal static string GroundfallFileName {
            get {
                return ResourceManager.GetString("GroundfallFileName", resourceCulture);
            }
        }
        
        internal static string ParticleSpriteFileName {
            get {
                return ResourceManager.GetString("ParticleSpriteFileName", resourceCulture);
            }
        }
    }
}
