//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltraFoxyChickenFlightX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltraFoxyChickenFlightX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\angry cloud1.png.
        /// </summary>
        internal static string AngryCloudFileName1 {
            get {
                return ResourceManager.GetString("AngryCloudFileName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\angry cloud2.png.
        /// </summary>
        internal static string AngryCloudFileName2 {
            get {
                return ResourceManager.GetString("AngryCloudFileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\thunder.ogg.
        /// </summary>
        internal static string AngryCloudSoundName {
            get {
                return ResourceManager.GetString("AngryCloudSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\bg.png.
        /// </summary>
        internal static string BackgroundFileName {
            get {
                return ResourceManager.GetString("BackgroundFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\backgroundmusic.ogg.
        /// </summary>
        internal static string BackgroundMusicFileName {
            get {
                return ResourceManager.GetString("BackgroundMusicFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\treffer grantre.ogg.
        /// </summary>
        internal static string BadTreeSoundName {
            get {
                return ResourceManager.GetString("BadTreeSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\furutre.png.
        /// </summary>
        internal static string BadTreeSpriteFileName {
            get {
                return ResourceManager.GetString("BadTreeSpriteFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\chicken house rustle.ogg.
        /// </summary>
        internal static string ChickenRustleMusicFIleName {
            get {
                return ResourceManager.GetString("ChickenRustleMusicFIleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\farmer.png.
        /// </summary>
        internal static string FarmerFileName {
            get {
                return ResourceManager.GetString("FarmerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\foxyhappy1.png.
        /// </summary>
        internal static string FoxyHappy1FileName {
            get {
                return ResourceManager.GetString("FoxyHappy1FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\foxyhappy2.png.
        /// </summary>
        internal static string FoxyHappy2FileName {
            get {
                return ResourceManager.GetString("FoxyHappy2FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\foxyscared1.png.
        /// </summary>
        internal static string FoxyScared1FileName {
            get {
                return ResourceManager.GetString("FoxyScared1FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\foxyscared2.png.
        /// </summary>
        internal static string FoxyScared2FileName {
            get {
                return ResourceManager.GetString("FoxyScared2FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\foxystanding.png.
        /// </summary>
        internal static string FoxyStandingFileName {
            get {
                return ResourceManager.GetString("FoxyStandingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\bush.ogg.
        /// </summary>
        internal static string GoodTreeSoundName {
            get {
                return ResourceManager.GetString("GoodTreeSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\epletre.png.
        /// </summary>
        internal static string GoodTreeSpriteFileName {
            get {
                return ResourceManager.GetString("GoodTreeSpriteFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\happycloud1.png.
        /// </summary>
        internal static string HappyCloudFileName1 {
            get {
                return ResourceManager.GetString("HappyCloudFileName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\happycloud2.png.
        /// </summary>
        internal static string HappyCloudFileName2 {
            get {
                return ResourceManager.GetString("HappyCloudFileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\englesky.ogg.
        /// </summary>
        internal static string HappyCloudSoundName {
            get {
                return ResourceManager.GetString("HappyCloudSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\henhouse.png.
        /// </summary>
        internal static string HenhouseFileName {
            get {
                return ResourceManager.GetString("HenhouseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\UltraFoxyChickenFlightX.png.
        /// </summary>
        internal static string LogoFileName {
            get {
                return ResourceManager.GetString("LogoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\new_game_hover.png.
        /// </summary>
        internal static string MainMenuNewGameHoverFileName {
            get {
                return ResourceManager.GetString("MainMenuNewGameHoverFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\quit_hover.png.
        /// </summary>
        internal static string MainMenuQuitHoverFileName {
            get {
                return ResourceManager.GetString("MainMenuQuitHoverFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\MenuSoundtrack.ogg.
        /// </summary>
        internal static string MainMenuSoundName {
            get {
                return ResourceManager.GetString("MainMenuSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resouces\continue.png.
        /// </summary>
        internal static string MenuContinueFileName {
            get {
                return ResourceManager.GetString("MenuContinueFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\UltraFOxyChickenFlightX.png.
        /// </summary>
        internal static string MenuGameTitleFileName {
            get {
                return ResourceManager.GetString("MenuGameTitleFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\new_game.png.
        /// </summary>
        internal static string MenuNewGameFileName {
            get {
                return ResourceManager.GetString("MenuNewGameFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\quit.png.
        /// </summary>
        internal static string MenuQuitFileName {
            get {
                return ResourceManager.GetString("MenuQuitFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\0_9.png.
        /// </summary>
        internal static string NumbersSpriteFileName {
            get {
                return ResourceManager.GetString("NumbersSpriteFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\wind.ogg.
        /// </summary>
        internal static string WindFileName {
            get {
                return ResourceManager.GetString("WindFileName", resourceCulture);
            }
        }
    }
}
